// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Haegc_y_0_m5YOiAYJRIYHFKKTTm2p4',
    appId: '1:176332816500:web:7d49ca5bea0ad76740d121',
    messagingSenderId: '176332816500',
    projectId: 'my-app-test-bac71',
    authDomain: 'my-app-test-bac71.firebaseapp.com',
    storageBucket: 'my-app-test-bac71.appspot.com',
    measurementId: 'G-DXZG4P2VED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx1LI5HsW1r5z9iPNP4NCt-3lWSL0rtGw',
    appId: '1:176332816500:android:87b0450fe506a7a340d121',
    messagingSenderId: '176332816500',
    projectId: 'my-app-test-bac71',
    storageBucket: 'my-app-test-bac71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUYmVj-tiE5tlLqzgeImJQhXFw0ejvj20',
    appId: '1:176332816500:ios:e2cce30379e0a6d440d121',
    messagingSenderId: '176332816500',
    projectId: 'my-app-test-bac71',
    storageBucket: 'my-app-test-bac71.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUYmVj-tiE5tlLqzgeImJQhXFw0ejvj20',
    appId: '1:176332816500:ios:e2cce30379e0a6d440d121',
    messagingSenderId: '176332816500',
    projectId: 'my-app-test-bac71',
    storageBucket: 'my-app-test-bac71.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0Haegc_y_0_m5YOiAYJRIYHFKKTTm2p4',
    appId: '1:176332816500:web:5654c65247c01b9940d121',
    messagingSenderId: '176332816500',
    projectId: 'my-app-test-bac71',
    authDomain: 'my-app-test-bac71.firebaseapp.com',
    storageBucket: 'my-app-test-bac71.appspot.com',
    measurementId: 'G-JM3KWDK1KK',
  );
}
